spring:
  application:
    name: know_your_customer
  datasource:
    url: jdbc:postgresql://localhost:5432/documentKYC_db
    username: kyc
    password: kyc
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8090

app:
  secret-key : HxIQwcjmqw7nviqaxC7NLBAG6vL1bakC0d3lu8nisUYtfJMMHj0JPRPRzGyJ2KNN
  expiration-time : 900000

